### PR TITLE
Update capacity-planning-and-load-testing-sharepoint-online.md

### PR DESCRIPTION
**Pull request by Stealth7777**
Changed link to Tune SharePoint Online performance. No need to update the change / modified date

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
Copy edited - no changes.

**Comment by KCCross** [comment]
Actually, this piece now belongs to Kelley Vice. Please redirect. Thanks! Thanks for the heads up as this recently changed hands. Kelley, we probably need to change the author field still.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mypil** [comment]
@KCCross - may I know the Github login of Kelley Vice so we can tag her on this PR? Or could you possibly tag her on this PR? Thanks.

**Comment by mypil** [comment]
@kelleyvice-msft - can you please assist to check, approve and merge the content for this PR?

Thank you.

**Comment by kelleyvice-msft** [comment]
Approved and merging. @KCCross - I'll update the author field.

**Pull request merged**
