### PR TITLE
Updated some minor text tweaks

### PR DESCRIPTION
**Pull request by Stealth7777**
@kelleyvice-msft Tweaked some wording and version detail at the top

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by kelleyvice-msft** [comment]
Thanks Joyce. The PM committed this to the Enterprise repo instead of Enterprise-pr. I don’t know if I’ve seen how that works before. Any issues with doing it that way?

{
  "parameters": {
    "Kelley Vice": {
    "type": "Senior Content Developer"
    }
  },
  "variables": {
    "roles": [
      "M365/O365 Networking and Performance",
      "MARVEL Skunkworks Lab Operations"
    ],
    "mobile": "206.713.5850",
    "office": "425.707.7315"
  }
}
[cid:image001.png@01D552BA.C211AA70]

**Comment by mypil** [comment]
@kelleyvice-msft - No issues at all. That's alright since you've already reviewed the PR content and merged it. Thank you.

**Comment by kelleyvice-msft** [comment]
Joyce, I still don’t see the updates in the live topic: https://docs.microsoft.com/en-us/office365/enterprise/page-diagnostics-for-spo. Is there something else I need to do?

Thanks!

{
  "parameters": {
    "Kelley Vice": {
    "type": "Senior Content Developer"
    }
  },
  "variables": {
    "roles": [
      "M365/O365 Networking and Performance",
      "MARVEL Skunkworks Lab Operations"
    ],
    "mobile": "206.713.5850",
    "office": "425.707.7315"
  }
}
[cid:image001.png@01D552BA.C211AA70]

**Comment by mypil** [comment]
@kelleyvice-msft -  I have not encountered an issue like you mentioned before so I'm also not sure how to resolve that. Could it be that it needs some time for the merged content to appear in the live doc?

**Comment by kelleyvice-msft** [comment]
@mypil - Maybe, but it's been a few hours. Can I just revert this commit and create a new PR using the normal method?

**Comment by mypil** [comment]
@kelleyvice-msft - Yes, I think it is possible for you to do that.

**Comment by kelleyvice-msft** [comment]
Thanks, @mypil. I'll try that.

**Pull request merged**
