### PR TITLE
Update office-365-inter-tenant-collaboration.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the answer to question What about hybrid components and Office 365 inter-tenant collaboration? As AD connect can be split across MT.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue #https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/675

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #675.

Thank you.

cc: @kenwith

**Comment by chrfox** [comment]
The requested change is incorrect.

**Comment by chrfox** [comment]
refer to this topic for supported configurations https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-connect-topologies

**Pull request closed without merging**
