### PR TITLE
add info about SharePoint Administrator

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/705

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #705.

Thank you.

cc: @kenwith

**Comment by MikePlumleyMSFT** [comment]
@AdwoodMicrosoft can you confirm the permissions necessary to change the PDL on a group? We're using Exchange PowerShell, so I'm assuming a SharePoint admin can't do it.

**Comment by mypil** [comment]
@MikePlumleyMSFT @AdwoodMicrosoft - Do you have some updates on this?

**Pull request merged**
