### PR TITLE
Update office-365-core-principles-of-defense-against-dos-attacks.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed time to impact to Sec

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/780

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@robmazz - PR has been copy edited and is ready for final review. This is based on issue #780 

Thank you.

cc: @kenwith

**Comment by robmazz** [comment]
@msbemba - thanks for the feedback and suggestion!

**Pull request merged**
