### PR TITLE
update office-365-multi-geo.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
issue #273 
added the minimum seats requirements.
Source: [Get global data location controls with Multi-Geo](https://products.office.com/business/multi-geo-capabilities)

Also fixed links in the "See also" section

### CODE REVIEW

**Comment by mypil** [comment]
@MikePlumleyMSFT - can you please assist to check, approve and merge the content for this PR based on issue #273?

Thank you.

**Comment by mypil** [comment]
@MikePlumleyMSFT - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #273?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - would you be able to merge the content of this PR? Thanks.

**Comment by robmazz** [comment]
@pamgreen-msft - I know Mike is on leave, who should be reviewing PRs for his content?

**Comment by pamgreen-msft** [comment]
@JoanneHendrickson can you take a look at this PR too? Thanks!

**Comment by JoanneHendrickson** [comment]
looks good

**Pull request merged**
