### PR TITLE
Update office-365-client-support-modern-authentication.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Ipados to the Supported Platforms

### CODE REVIEW

**Comment by msbemba** [comment]
Issue# https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/783

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@robmazz - PR has been copy edited and is ready for final review. This is based on issue #783

Thank you.

cc: @kenwith

**Comment by robmazz** [comment]
@msbemba - thanks for the feedback. I will confirm this potential change with our Customer Promises Team, we are in the midst of updating and reworking our plan for these topics.

**Pull request closed without merging**
