### PR TITLE
Small edit to provide examples of external ranges

### PR DESCRIPTION
**Pull request by dzazzo-msft**
Added a small example of URL and IP address range in CIDR notation per internal feedback to reduce customer confusion.

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@dzazzo-msft - It appears that you are the author for this doc. Are you able to merge this PR or do you want us to reach out to another author with merging rights to merge this? Please advise. 

Thank you.

cc: @kenwith

**Comment by dzazzo-msft** [comment]
@mypil - I don’t have merge rights yet. If you could reach out to another author (or I can), that’s be helpful.

**Comment by mypil** [comment]
@JoeDavies-MSFT @chrisda @kenwith - Can anyone of you please assist to merge this PR? 

Thank you.

cc: @kenwith

**Comment by kelleyvice-msft** [comment]
@dzazzo-msft - sending me an email with a link to the PR is the best way to do this. Thanks!

**Pull request merged**
