### PR TITLE
Update office-365-multi-geo.md

### PR DESCRIPTION
**Pull request by msbemba**
Added pricing and licensing

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #812.

Thank you.

cc: @kenwith

**Comment by MikePlumleyMSFT** [comment]
@AdwoodMicrosoft can you review? Are you okay with having licensing info here? I couldn't find a good place to link to.

**Comment by mypil** [comment]
@MikePlumleyMSFT @AdwoodMicrosoft - We would like to follow up on this. Do you have any updates?

Thank you.

**Pull request merged**
