### PR TITLE
Updated office-365-ip-web-service.md

### PR DESCRIPTION
**Pull request by kelleyvice-msft**
This PR incorporates multiple edits from others that resulted in a conflict. I've added revisions of my own to wording, formatting and added a note re the spelling of the cmdlet Invoke-O365EnpointService, which does not include the letter d.

### CODE REVIEW

**Comment by mypil** [comment]
@kelleyvice-msft - is this PR related to #401? Should we still let @ojrb create a new PR for issue #321 & #377. There appears to still have some conflicts on this PR. Kindly advise how to proceed. Thank you.

**Comment by kelleyvice-msft** [comment]
@mypil and @ojrb - I created this PR to try and get rid of the conflict. I'll close this. @ojrb , what we need is a new PR that does not contain any conflicts, and does not contain a commit that deletes the file office-365-ip-web-service.md.

**Comment by mypil** [comment]
@kelleyvice-msft - Could it be that the issue is with the content source? 
@ojrb tested and I also tried accessing the content source ([Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)) but it went to a 404 page not found error.

**Comment by kelleyvice-msft** [comment]
@mypil - It looks like the file Enterprise/office-365-ip-web-service.md has been deleted from the repo by @ojrb in commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise-pr/commit/0209c25ae4d2411d71fe06d1448cb1b909c92eb1. It is also missing from the Enterprise-pr master branch, but still exists in the live branch, at least until someone does a merge. Does anyone know why this file was deleted? It most certainly should not be deleted.

**Comment by ojrb** [comment]
@mypil and @kelleyvice-msft  in the firsts PR, I used two files by mistake and generate other PR only with the correct files, yes I deleted the files from the PR (Obviously not for the master I don't have access to it) to have only the correct files committed ! may be this was my mistake (Very sorry about that). How cn be corrected this situation?

**Comment by kelleyvice-msft** [comment]
@ojrb & @mypil - I've created a new branch (https://github.com/MicrosoftDocs/OfficeDocs-Enterprise-pr/tree/kv-o365-ip-urls) to replace the file and update it with Orlando's edited revision. I'll publish it in a few minutes. Thanks, Orlando.

**Comment by mypil** [comment]
@kelleyvice-msft - Do we still need @ojrb to create a new PR or no need anymore? Kindly confirm. 

Thank you for your kind assistance.

**Comment by kelleyvice-msft** [comment]
@mypil and @ojrb - I did some finagling and published a new PR containing Orlando's revisions, so we're all good. Orlando, perhaps you can check the live topic and make sure I didn't miss anything.

**Comment by ojrb** [comment]
I review your commited file and all is Ok !  ! You didn't miss anything !

**Pull request closed without merging**
