### PR TITLE
Link update

### PR DESCRIPTION
**Pull request by joinimran**
Link is not pointing to the appropriate information.

Problem: https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/648

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@robmazz - PR has been copy edited and is ready for final review. This is based on issue #648.

Thank you.

cc: @kenwith

**Comment by robmazz** [comment]
@joinimran - thanks for the feedback, but I've updated the link to point directly to the redirected topic (which is the correct link). Closing this as unmerged, thanks!

**Comment by JimTheFrog** [comment]
This isn't fixed. If all you did is update the link, then it's still pointing to an **irrelevant page**. I just checked, and https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-data-retention-deletion-and-destruction-overview.md says "For more information on expedited de-provisioning, see Cancel Office 365," linking to https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/cancel-your-subscription?view=o365-worldwide, which still says nothing about **expedited de-provisioning**.

I'll say it again: You can't write "For more info on X see Y" when Y doesn't contain any info about X.

**Pull request closed without merging**
