### PR TITLE
Update office-365-network-mac-perf-onboarding-tool.md

### PR DESCRIPTION
**Pull request by AntoniaBlume**
Fix branding: We should NEVER abbreviate to "M365" in public-facing materials. Also, "admin center" should be lowercased.

### CODE REVIEW

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@AntoniaBlume - please make the necessary changes on the PR following the suggestions made by the copy/edit review done by JohanFreelancer9 . Thank you.

**Comment by mypil** [comment]
@kelleyvice-msft - PR has been copy edited but some suggested changes were not applied by the OP but we'll leave it up to you for your final review for merging.

Thank you.

cc: @kenwith

**Comment by AntoniaBlume** [comment]
Hi @Kelley Vice<mailto:Kelley.Vice@exchange.microsoft.com> and @Ken Withee<mailto:ken.withee@microsoft.com>, I am the original poster, but not a usual contributor to GitHub and was hoping you could take it from here, make the judgement call of what additional edits to make and apply those changes. Is the only way forward that I need to learn how to merge changes and publish? Can you do that on my behalf in the interest of time?

Thank you!

Antonia

**Pull request merged**
