### PR TITLE
Changes in XML syntax

### PR DESCRIPTION
**Pull request by joinimran**
The command was not executing as expected. Correction made.

Problem: https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/626

### CODE REVIEW

**Comment by joinimran** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by joinimran** [comment]
@mypil Ready to go live.

**Comment by mypil** [comment]
@kelleyvice-msft @smithre4 - PR has been copy edited and is ready for final review. This is based on issue #626

Thank you.

cc: @kenwith

**Comment by smithre4** [comment]
looks good to me. I don't have an environment to test this, so will have to take submitters word that this does work :)

**Comment by mypil** [comment]
@smithre4 -  Since this has been approved, would you be able to merge this PR? Thank you.

**Comment by smithre4** [comment]
I don't have that capability.

**Pull request merged**
