### PR TITLE
Pull Request for Issue #395

### PR DESCRIPTION
**Pull request by ojrb**
Update the document as requested, deleting the complete reference for the broken link as requested. This solve the issue #395

### CODE REVIEW

**Comment by mypil** [comment]
@MSFTTracyP - Can you please assist to check, approve and merge the content for this PR based on issue #395?

Thank you.

**Comment by mypil** [comment]
@MSFTTracyP - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #395? Thank you.

cc: @LauraWi

**Comment by mypil** [comment]
@MSFTTracyP - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #395? Thank you.

**Comment by LauraWi** [comment]
Looping in @Tracy Paddock<mailto:tracyp@microsoft.com>

**Comment by mypil** [comment]
@MSFTTracyP - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #395? Thank you.

**Pull request merged**
